version: '3'

services:
  app:
    build: .
    environment:
       #PostgreSQL Config
       - DURATION=2
       - DRIVER=postgresql
       - PGHOST=postgres
       - PGPORT=5432
       - PGDATABASE=test
       - PGUSERNAME=test
       - PGPASSWORD=test
       - COUNT=5

      # MongoDB Config
      - DURATION=30
      - DRIVER=mongodb
      - MDHOST=mongo
      - MDPORT=27017
      - MDDATABASE=test
      - MDUSERNAME=test
      - MDPASSWORD=test
      - MDAUTHDB=admin
      - COUNT=5
    volumes:
      - "backups:/var/scripts/backup/backups"
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
volumes:
  backups:
